version: '2.2'
# docker-compose.yml
services:
  app:
    image: informationcatalyst/meteorapp002
    ports:
      - "7888:3000"
    links:
       - mongo
    depends_on:
      - mongo
    environment:
      - ROOT_URL=http://example.com
      - MONGO_URL=mongodb://mongo:27017

  mongo:
    image: mongo:latest
    command: mongod --storageEngine=wiredTiger
    volumes: 
      - $PWD/data-db:/data/db

